[project]
name = "scientific-python-hugo-theme"
version = "0.12"

[tool.changelist]
# Profiles that are excluded from the contributor list.
ignored_user_logins = ["dependabot[bot]", "pre-commit-ci[bot]", "web-flow"]
